//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_A_Car.Repo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RACEntities : DbContext
    {
        public RACEntities()
            : base("name=RACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DriverLicences> DriverLicences { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<LicencePlates> LicencePlates { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<RentCalendar> RentCalendar { get; set; }
        public virtual DbSet<ResCalendar> ResCalendar { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
    }
}
